### ISSUE TITLE
new NuGet package for the NancyFx 2.0.0.0 release?

### ISSUE THREAD

**Issue by kevegabi** [NancyFx/Nancy.MSOwinSecurity#16]
Hello!

Tha main project 2.0.0.0 version released a weeks ago. The current Nancy.MSOWinSecurity not compatible that version (>= 1.0.0.0 && < 2.0.0.0). Do you have a plan to update the NuGetpackage to the current version?

Thanks,
Gabor

**Comment by ravenpride** [comment]
I've added support for NancyFx v2, a [PR](https://github.com/NancyFx/Nancy.MSOwinSecurity/pull/17) is pending. This might help you until the PR is accepted.

**Comment by damianh** [comment]
https://www.nuget.org/packages/Nancy.MSOwinSecurity/3.0.0
