### ISSUE TITLE
RequiresSecurityClaims

### ISSUE THREAD

**Issue by pjirsa** [NancyFx/Nancy.MSOwinSecurity#7]
When trying to call that method (using the sample code) i get an error that "claim" does not exist in the current context. My linq skills are a little weak. What am I missing?

**Comment by damianh** [comment]
Can you share your code so I can reproduce?

**Comment by pjirsa** [comment]
was trying to use this from the sample
  this.RequiresSecurityClaims(claims => claims.Any(
    claim.ClaimType = ClaimTypes.Country &&
    claim.Value.Equals("IE", StringComparision.Ordinal)));

got it to work like this:
  this.RequiresSecurityClaims(claims => claims.Any(claim => 
    claim.ClaimType = ClaimTypes.Country &&
    claim.Value.Equals("IE", StringComparision.Ordinal)));

**Comment by damianh** [comment]
Updated wiki.
