### ISSUE TITLE
Requires Scope

### ISSUE THREAD

**Issue by dealproc** [NancyFx/Nancy.MSOwinSecurity#8]
Not sure if this is something specific to OAuth or not, but would a RequiresScope be worthwhile?

**Comment by damianh** [comment]
This package is mostly about integration with MS's `IAuthenticatonManager` which is about `ClaimsPrincipal`. 

The answer is "I don't know" but my gut is saying it wouldn't feel right.

**Comment by damianh** [comment]
Am open to being educated on this...

**Comment by dealproc** [comment]
In Thinktecture IdentityModel, you are provided with the following:

https://github.com/IdentityModel/Thinktecture.IdentityModel/blob/master/source/WebApi.ScopeAuthorization/ScopeAuthorizeAttribute.cs

I'm possibly being lazy, as it's just a specific claim type, but it expresses intent a bit more fluently.  Not sure exactly with the OAuth2 spec, but as I recall, one of the claims you get back from IdentityServer is specifically "Scope" that can be utilized to decide what sections of the system you have access to.  Dominick offered this, I believe, to be able to better break-up the system into areas of concern.

**Comment by leastprivilege** [comment]
OAuth defines scopes - and the mentioned attribute is an Web API authorize attribute that checks for the presence of a given scope claim.

So in Nance - RequiresScope would be similar to that.

But not in this repo - as Damian said this is all about Katana integration.

**Comment by dealproc** [comment]
Ok.  No worries.  Thx @leastprivilege for the clarification.

**Comment by damianh** [comment]
I do have [this extension though](https://github.com/NancyFx/Nancy.MSOwinSecurity/blob/master/src/Nancy.MSOwinSecurity/NancyModuleExtensions.cs#L31)

@dealproc you may have a point. But Nancy v2 is in the works and since it uses ClaimsPrincipal, I'll prob have to update this repo to remove this extension.
